version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.2-stretch-browsers
        environment:
          MYSQL_HOST: 127.0.0.1
          MYSQL_DB: mydb
          MYSQL_USER: root
          MYSQL_PASSWORD: root
      - image: mysql:5.6
        environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: mydb
    steps:
      - checkout

      - run: mkdir test-reports

      - run:
          name: Download Selenium
          command: |
            curl -O http://selenium-release.storage.googleapis.com/3.5/selenium-server-standalone-3.5.3.jar
            
      - run:
          name: Start Selenium
          command: |
            java -jar selenium-server-standalone-3.5.3.jar -log test-reports/selenium.log
          background: true

      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}

      - run:
          name: Install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"

      - run:
          name: Wait for MySQL
          command: dockerize -wait tcp://localhost:3306 -timeout 1m

      - run:
          name: Run unit tests
          command: |
            python3 -m venv venv
            . venv/bin/activate
            python app/tests.py

      - setup_remote_docker

      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            sudo mv -f /tmp/docker/* /usr/bin

      - run:
         name: Build Docker image
         command: docker build -t kartisuri/movies-store:$CIRCLE_SHA1 .

      - run:
          name: Push to DockerHub
          command: |
            docker login -u$DOCKERHUB_LOGIN -p$DOCKERHUB_PASSWORD
            docker push kartisuri/movies-store:$CIRCLE_SHA1

      - run:
          name: Setup Heroku
          command: |
            chmod +x .circleci/setup-heroku.sh
            .circleci/setup-heroku.sh

      - run:
          name: Deploy to Heroku
          command: |
            cd app/
            git push heroku master
